/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumahsakitmahsa13457;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Mahsa
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
        excute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setPreferredSize(new java.awt.Dimension(502, 436));

        pn_navbar.setBackground(new java.awt.Color(0, 102, 51));
        pn_navbar.setPreferredSize(new java.awt.Dimension(500, 70));

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem Manajement Rumah Sakit");

        jLabel1.setBackground(new java.awt.Color(204, 255, 102));
        jLabel1.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIMARS");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(204, 204, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 317));

        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(153, 255, 153));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(153, 255, 153));

        pn_utama.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(204, 255, 102));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistem Manajement Rumah Sakit ");

        jLabel4.setBackground(new java.awt.Color(204, 255, 102));
        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("©MAHSARAHIMA MEDICAL CENTER ");

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addGroup(pn_contentLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(650, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void excute() {
        ImageIcon iconData = new ImageIcon(getClass().getResource("/icon/foldersmini.png"));
        ImageIcon iconDokter = new ImageIcon(getClass().getResource("/icon/doktermini.png"));
        ImageIcon iconPasien = new ImageIcon(getClass().getResource("/icon/pasienmini.png"));
        ImageIcon iconObat = new ImageIcon(getClass().getResource("/icon/medicinemini.png"));
        ImageIcon iconRekmedis = new ImageIcon(getClass().getResource("/icon/rekmedismini.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/icon/notamini.png"));
        ImageIcon iconRawatJalan = new ImageIcon(getClass().getResource("/icon/pasienrawatmini.png"));
        ImageIcon iconKeluar = new ImageIcon(getClass().getResource("/icon/logoutmini.png"));
        ImageIcon iconLaporan = new ImageIcon(getClass().getResource("/icon/laporanmini.png"));
        ImageIcon iconPDF = new ImageIcon(getClass().getResource("/icon/pdfmini.png"));
        ImageIcon iconExcel = new ImageIcon(getClass().getResource("/icon/Excelmini.png"));
        ImageIcon iconUtility = new ImageIcon(getClass().getResource("/icon/utilitymini.png"));
        ImageIcon iconBackUp = new ImageIcon(getClass().getResource("/icon/backupmini.png"));
        ImageIcon iconAdmin = new ImageIcon(getClass().getResource("/icon/adminmini.png"));

        
        MenuItem menuDokter = new MenuItem(null, true, iconDokter, "Data Dokter", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new dataDokter().setVisible(true);
            }
        });
        MenuItem menuPasien = new MenuItem(null, true, iconPasien, "Data Pasien", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new dataPasien().setVisible(true);
            }
        });
        MenuItem menuObat = new MenuItem(null, true, iconObat , "Data Obat ", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new dataObat ().setVisible(true);
            }
        });
        MenuItem menuRekamMedis = new MenuItem(null, true, iconRekmedis, "Rekam Medis", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new dataRekamMedis().setVisible(true);
            }
        });
        MenuItem menuMaster = new MenuItem(iconData, false, null, "Master", null, 
                    menuDokter, menuPasien,menuObat,menuRekamMedis);
        MenuItem menuRawatJalan = new MenuItem(null, true, iconRawatJalan, "Rawat Jalan", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new rawatJalan().setVisible(true);
            }
        });
        MenuItem menuTransaksi = new MenuItem(iconTransaksi, false, null, "Transaksi", null,menuRawatJalan);
        
        MenuItem menuLapPasienpdf = new MenuItem(null, true, iconPDF, "Laporan PDF", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new LapPasien().setVisible(true);
            }
        });
        MenuItem menuLapPasienexcel = new MenuItem(null, true, iconExcel, "Laporan Excel", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new LapPasien().setVisible(true);
            }
        });
        MenuItem menuLaporan = new MenuItem(iconLaporan, false, null, "Laporan", null,menuLapPasienpdf,menuLapPasienexcel);
        MenuItem menuBackup = new MenuItem(null, true, iconBackUp, "Back Up", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new frmBackupDb().setVisible(true);
            }
        });
        MenuItem menuAdmin = new MenuItem(null, true, iconAdmin, "Admin", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                new frmLoginAdmin().setVisible(true);
            }
        });
        MenuItem menuUtility = new MenuItem(iconUtility, false, null, "Utility", null,menuBackup, menuAdmin);

        MenuItem menuKeluar = new MenuItem(iconKeluar, false, null, "Keluar", new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                dispose();
            }
        });
        
        addMenu(menuMaster, menuTransaksi, menuLaporan,menuUtility,menuKeluar);
    }
    private void addMenu(MenuItem... menu) {
        for(int i=0; i < menu.length; i++){
            pn_menu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for(MenuItem m : subMenu){
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }
}
